from .classic_tasks import cifar_dataset
from .classic_tasks import oneHotEncoding
from .classic_tasks import mnist_dataset
#from .extra_tasks import emnistABFL_CHIS
#from .extra_tasks import emnistABEL_CHJS
from .synthetic_tasks import synthetic_1hl_dataset
from .synthetic_tasks import linear_dataset
from .synthetic_tasks import single_index_dataset
from .synthetic_tasks import hermite_dataset
from .synthetic_tasks import add_first_layer_bias